"""first

Revision ID: 70f362aa810d
Revises: 
Create Date: 2021-11-09 21:22:13.976285

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '70f362aa810d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.BLOB(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'picture'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('picture')
    )
    op.create_table('gifs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.BLOB(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['images.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gifs')
    op.drop_table('images')
    # ### end Alembic commands ###
